MONGO_URI = "mongodb+srv://infactdb-user:Test123_@cluster0.oz9rv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
ADMIN_KEY = "infactadmin"
OPENAI_API_KEY = "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"